Game:
  name: Donkey Kong
  Paths:
    folder: "Mesen.0.9.9\\"
    emulator: "Mesen.0.9.9\\Mesen.exe"
    game: "Donkey Kong\\Donkey Kong (USA) (GameCube Edition).nes"
  Emulator_State:
    RecentGames_Path: "Emulator_State\\RecentGames\\"
    SaveStates_Path: "Emulator_State\\SaveStates\\"

Tensorflow:
  Features:
  # These are the ascii value of the keys
  Targets:
    s key: 73
    left arrow: 37
    up arrow: 38
    right arrow: 39
  log_level: '2'

Photo_Analysis:
  Path:
    folder: "Photo_Analysis\\"
  Settings: